-- CAPÍTULO 5: MATRÍCULAS

CREATE TABLE Matriculas (
    ID_Matricula NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    ID_Turma NUMBER NOT NULL,
    ID_Aluno NUMBER NOT NULL,
    Token_Acesso VARCHAR2(50), -- Chave única p/ avaliações
    ID_Estado_Matricula NUMBER,
    Data_Inscricao DATE DEFAULT SYSDATE,
    Diagnostico_Respostas CLOB, -- JSON das respostas iniciais
    Data_Conclusao DATE,
    Classificacao_Final VARCHAR2(50),
    Total_Horas NUMBER,
    Avaliacao_Curso NUMBER,
    Comentario_Aluno CLOB,
    Obs_SIGO VARCHAR2(4000),
    ID_Nivel_Experiencia NUMBER,
    
    FOREIGN KEY (ID_Turma) REFERENCES Turmas(ID_Turma),
    FOREIGN KEY (ID_Aluno) REFERENCES Entidades(ID_Entidade),
    FOREIGN KEY (ID_Estado_Matricula) REFERENCES Tipos_Estado_Matricula(ID_Estado_Matricula)
);

-- Evitar duplicados: um aluno só se matricula 1 vez na mesma turma
CREATE UNIQUE INDEX UK_Matricula_Aluno_Turma ON Matriculas(ID_Turma, ID_Aluno);
