-- CAPÍTULO 5B: INSCRIÇÕES (Antiga Pré-Inscrição/Interesse)
-- Tabela para registar o interesse explícito de uma entidade num curso (Candidatura)

-- Reset: Apagar tabela antiga se existir (CUIDADO: Limpa os dados!)
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE Inscricoes CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN -- 942: table or view does not exist
            RAISE;
        END IF;
END;
/

CREATE TABLE Inscricoes (
    ID_Inscricao NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    ID_Curso NUMBER NOT NULL,
    ID_Entidade NUMBER NOT NULL,
    ID_Turma_Preferencia NUMBER, -- NOVA COLUNA: Se o cidadão escolheu uma turma específica
    Data_Registo DATE DEFAULT SYSDATE,
    Origem VARCHAR2(50), -- 'PORTAL', 'BACKOFFICE', 'IMPORT'
    Respostas_Diagnostico CLOB, -- JSON com dados do diagnóstico inicial
    Estado_Inscricao VARCHAR2(50) DEFAULT 'PENDENTE', 
    Observacoes VARCHAR2(4000),
    
    CONSTRAINT FK_Ins_Curso FOREIGN KEY (ID_Curso) REFERENCES Cursos(ID_Curso),
    CONSTRAINT FK_Ins_Entidade FOREIGN KEY (ID_Entidade) REFERENCES Entidades(ID_Entidade),
    CONSTRAINT FK_Ins_TurmaPref FOREIGN KEY (ID_Turma_Preferencia) REFERENCES Turmas(ID_Turma)
);

-- Evitar duplicados
CREATE UNIQUE INDEX UK_Ins_Curso_Entidade ON Inscricoes(ID_Curso, ID_Entidade);
