-- CAPÍTULO 5B: PRÉ-INSCRIÇÕES (INTERESSE)
-- Tabela para registar o interesse explícito de uma entidade num curso

CREATE TABLE Pre_Inscricoes (
    ID_Pre_Inscricao NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    ID_Curso NUMBER NOT NULL,
    ID_Entidade NUMBER NOT NULL,
    Data_Registo DATE DEFAULT SYSDATE,
    Origem VARCHAR2(50), -- 'PORTAL', 'BACKOFFICE', 'IMPORT'
    Respostas_Diagnostico CLOB, -- JSON com dados do diagnóstico inicial (Vindo do Excel/Form)
    Observacoes VARCHAR2(4000),
    
    CONSTRAINT FK_PreIns_Curso FOREIGN KEY (ID_Curso) REFERENCES Cursos(ID_Curso),
    CONSTRAINT FK_PreIns_Entidade FOREIGN KEY (ID_Entidade) REFERENCES Entidades(ID_Entidade)
);

-- Evitar duplicados
CREATE UNIQUE INDEX UK_PreIns_Curso_Entidade ON Pre_Inscricoes(ID_Curso, ID_Entidade);
