-- 06_Pedagogia.sql
-- Capítulo 6: Execução Pedagógica (Unified Script)
-- Inclui tabelas para Presenças, Avaliações e Gestão de Medalhas

-- 1. Presenças (Assiduidade por Sessão)
CREATE TABLE Presencas (
    ID_Presenca NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    ID_Sessao NUMBER NOT NULL,
    ID_Matricula NUMBER NOT NULL,
    ID_Estado_Presenca NUMBER, -- Opcional: Lookup para 'Presente', 'Falta Injustificada', etc.
    Horas_Assistidas NUMBER,
    Data_Registo TIMESTAMP DEFAULT SYSTIMESTAMP,
    FOREIGN KEY (ID_Sessao) REFERENCES Sessoes(ID_Sessao) ON DELETE CASCADE,
    FOREIGN KEY (ID_Matricula) REFERENCES Matriculas(ID_Matricula) ON DELETE CASCADE
);

-- 2. Avaliações (Notas por Módulo)
CREATE TABLE Avaliacoes_Modulo (
    ID_Avaliacao NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    ID_Matricula NUMBER NOT NULL,
    ID_Modulo NUMBER NOT NULL,
    Nota_Valor NUMBER,
    Feedback_Texto CLOB,
    Aprovado CHAR(1) CHECK (Aprovado IN ('S', 'N')),
    Data_Avaliacao DATE DEFAULT SYSDATE,
    FOREIGN KEY (ID_Matricula) REFERENCES Matriculas(ID_Matricula) ON DELETE CASCADE,
    FOREIGN KEY (ID_Modulo) REFERENCES Modulos(ID_Modulo) ON DELETE CASCADE
);

-- 3. Badges Conquistados (Histórico do Aluno)
CREATE TABLE Badges_Conquistados (
    ID_Badge_Aluno NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    ID_Matricula NUMBER NOT NULL,
    ID_Medalha NUMBER NOT NULL,
    ID_Turma NUMBER NOT NULL,
    Data_Conquista DATE DEFAULT SYSDATE,
    URL_Evidencia VARCHAR2(500),
    Token_Validacao VARCHAR2(100),
    FOREIGN KEY (ID_Matricula) REFERENCES Matriculas(ID_Matricula) ON DELETE CASCADE,
    FOREIGN KEY (ID_Medalha) REFERENCES Catalogo_Medalhas(ID_Medalha) ON DELETE CASCADE,
    FOREIGN KEY (ID_Turma) REFERENCES Turmas(ID_Turma) ON DELETE CASCADE
);

-- 4. Turma Medalhas Elegiveis (Quais medalhas o formador pode dar nesta turma)
CREATE TABLE Turma_Medalhas_Elegiveis (
    ID_Turma NUMBER NOT NULL,
    ID_Medalha NUMBER NOT NULL,
    Selecionado_Por VARCHAR2(100),
    Data_Selecao DATE DEFAULT SYSDATE,
    PRIMARY KEY (ID_Turma, ID_Medalha),
    FOREIGN KEY (ID_Turma) REFERENCES Turmas(ID_Turma) ON DELETE CASCADE,
    FOREIGN KEY (ID_Medalha) REFERENCES Catalogo_Medalhas(ID_Medalha) ON DELETE CASCADE
);

-- Indices para Performance
CREATE INDEX IDX_Presencas_Sessao ON Presencas(ID_Sessao);
CREATE INDEX IDX_Avaliacoes_Matricula ON Avaliacoes_Modulo(ID_Matricula);
CREATE INDEX IDX_Badges_Aluno ON Badges_Conquistados(ID_Matricula);
