-- 07_Admin.sql
-- Capítulo 7: Administração e Conformidade
-- Objetivo: Suportar Faturação, Dossier Pedagógico e Gestão de Equipamentos.
-- Data: 25-Jan-2026

-- 0. Garantir Lookups Necessários (Defensivo)
-- Caso não tenham sido criados anteriormente (ex: 01_Dominios.sql em falta)

-- 0.1 Tipos_Documento_Dossier
DECLARE
    v_count NUMBER;
BEGIN
    SELECT count(*) INTO v_count FROM user_tables WHERE table_name = 'TIPOS_DOCUMENTO_DOSSIER';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'CREATE TABLE Tipos_Documento_Dossier (
            ID_Tipo_Doc NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
            Codigo VARCHAR2(50) UNIQUE,
            Descricao VARCHAR2(200) NOT NULL,
            Obrigatorio CHAR(1) DEFAULT ''S'' CHECK (Obrigatorio IN (''S'',''N''))
        )';
    END IF;
END;
/

-- 0.2 Tipos_Equipamento
DECLARE
    v_count NUMBER;
BEGIN
    SELECT count(*) INTO v_count FROM user_tables WHERE table_name = 'TIPOS_EQUIPAMENTO';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'CREATE TABLE Tipos_Equipamento (
            ID_Tipo_Equipamento NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
            Codigo VARCHAR2(50) UNIQUE,
            Descricao VARCHAR2(200) NOT NULL
        )';
    END IF;
END;
/

-- 0.3 Garantir Dados de Seed (Lookups)
-- Mesmo que as tabelas existam, garantimos que os dados estão lá para as listas funcionarem.
BEGIN
    -- Tipos de Documento
    MERGE INTO Tipos_Documento_Dossier dest USING (
        SELECT 'SUMARIOS' as c, 'Sumários Assinados' as d, 'S' as o FROM DUAL UNION ALL
        SELECT 'PAUTA', 'Pauta de Avaliação', 'S' FROM DUAL UNION ALL
        SELECT 'PRESENCAS', 'Folha de Presenças', 'S' FROM DUAL UNION ALL
        SELECT 'CRONOGRAMA', 'Cronograma Final', 'N' FROM DUAL UNION ALL
        SELECT 'QUEST_SAT', 'Questionários de Satisfação', 'S' FROM DUAL
    ) src ON (dest.Codigo = src.c)
    WHEN NOT MATCHED THEN INSERT (Codigo, Descricao, Obrigatorio) VALUES (src.c, src.d, src.o);

    -- Tipos de Equipamento
    MERGE INTO Tipos_Equipamento dest USING (
        SELECT 'PC_PORTATIL' as c, 'PC Portátil' as d FROM DUAL UNION ALL
        SELECT 'TABLET', 'Tablet' FROM DUAL UNION ALL
        SELECT 'ROUTER', 'Router 4G/5G' FROM DUAL UNION ALL
        SELECT 'PROJECTOR', 'Projetor de Vídeo' FROM DUAL
    ) src ON (dest.Codigo = src.c)
    WHEN NOT MATCHED THEN INSERT (Codigo, Descricao) VALUES (src.c, src.d);

    COMMIT;
END;
/

-- 1. Checklist do Dossier Técnico-Pedagógico
-- Lista de documentos que devem existir por turma, com evidência (link/ficheiro) e validação.
CREATE TABLE Itens_Dossier_Turma (
    ID_Item_Dossier NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    ID_Turma NUMBER NOT NULL,
    ID_Tipo_Doc NUMBER NOT NULL,
    Presente CHAR(1) DEFAULT 'N' CHECK (Presente IN ('S', 'N')),
    URL_Ficheiro VARCHAR2(500),
    Validado_Por VARCHAR2(255),
    Data_Validacao DATE,
    Data_Upload DATE DEFAULT SYSDATE,
    Observacoes VARCHAR2(4000),
    
    FOREIGN KEY (ID_Turma) REFERENCES Turmas(ID_Turma) ON DELETE CASCADE,
    FOREIGN KEY (ID_Tipo_Doc) REFERENCES Tipos_Documento_Dossier(ID_Tipo_Doc)
);

-- Index Único: Um tipo de documento por turma (ex: só uma Pauta Final)
-- Se puder haver múltiplos, remover este índice único.
CREATE UNIQUE INDEX UK_Dossier_Turma_Doc ON Itens_Dossier_Turma(ID_Turma, ID_Tipo_Doc);


-- 2. Faturas de Formadores
-- Registo financeiro
CREATE TABLE Faturas_Formadores (
    ID_Fatura NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    ID_Formador NUMBER NOT NULL,
    ID_Turma NUMBER, -- Opcional, uma fatura pode referir-se a várias turmas ou a nenhuma específica
    Num_Fatura VARCHAR2(50),
    Valor NUMBER NOT NULL,
    Mes_Ref VARCHAR2(7), -- YYYY-MM
    Estado VARCHAR2(20) DEFAULT 'EMITIDA' CHECK (Estado IN ('EMITIDA', 'PAGA', 'CANCELADA')),
    Data_Emissao DATE,
    Data_Contabilistica DATE,
    Data_Pagamento DATE,
    Observacoes CLOB,
    
    FOREIGN KEY (ID_Turma) REFERENCES Turmas(ID_Turma) ON DELETE SET NULL,
    FOREIGN KEY (ID_Formador) REFERENCES Entidades(ID_Entidade) ON DELETE CASCADE
);


-- 3. Equipamentos (Hardware)
-- Alocação de recursos físicos a uma turma (ex: "Entregues 15 portáteis à turma X")
CREATE TABLE Equipamentos_Alocados (
    ID_Alocacao NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    ID_Turma NUMBER NOT NULL,
    ID_Tipo_Equipamento NUMBER NOT NULL,
    Quantidade NUMBER DEFAULT 1,
    Data_Entrega DATE DEFAULT SYSDATE,
    Data_Devolucao DATE,
    Estado_Conservacao VARCHAR2(200),
    Responsavel_Entrega VARCHAR2(200), -- Quem entregou
    Recebido_Por VARCHAR2(200), -- Quem recebeu (ex: formador)
    
    FOREIGN KEY (ID_Turma) REFERENCES Turmas(ID_Turma) ON DELETE CASCADE,
    FOREIGN KEY (ID_Tipo_Equipamento) REFERENCES Tipos_Equipamento(ID_Tipo_Equipamento)
);

-- Indices Performance
CREATE INDEX IDX_Faturas_Formador ON Faturas_Formadores(ID_Formador);
CREATE INDEX IDX_Equip_Turma ON Equipamentos_Alocados(ID_Turma);
