-- 08_Comunicacao.sql
-- Script para criar o sistema de Templates de Comunicação e Automação
-- Versão: 8.0

-- 1. Tabela de Templates (Modelos)
CREATE TABLE Modelos_Comunicacao (
    ID_Modelo       NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    Codigo_Ref      VARCHAR2(50) NOT NULL, -- Ex: 'BOAS_VINDAS'
    Assunto         VARCHAR2(200) NOT NULL,
    Corpo_HTML      CLOB,
    Contexto        VARCHAR2(20) DEFAULT 'GERAL', -- 'TURMA', 'ALUNO', 'GERAL'
    ID_Curso        NUMBER, -- Para "Overrides" específicos
    Ativo           CHAR(1) DEFAULT 'S' CHECK (Ativo IN ('S','N')),
    CONSTRAINT UK_Modelo_Ref_Curso UNIQUE (Codigo_Ref, ID_Curso)
);

-- 2. Tabela de Fila de Envio (Log & Queue)
CREATE TABLE Log_Comunicacoes (
    ID_Log          NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    Remetente       VARCHAR2(100) DEFAULT 'noreply@academiadigital.pt',
    Destinatario    VARCHAR2(255) NOT NULL,
    Assunto         VARCHAR2(200),
    Corpo_HTML      CLOB,
    Data_Criacao    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    Data_Agendada   TIMESTAMP DEFAULT CURRENT_TIMESTAMP, -- Para agendamento
    Data_Envio      TIMESTAMP,
    Estado          VARCHAR2(20) DEFAULT 'PENDENTE', -- PENDENTE, ENVIADO, ERRO
    Erro_Msg        VARCHAR2(4000),
    Contexto_Origem VARCHAR2(50) -- Ex: 'TURMA:10'
);

-- 3. Inserir Dados de Exemplo (Seed Data)
INSERT INTO Modelos_Comunicacao (Codigo_Ref, Assunto, Contexto, Corpo_HTML)
VALUES (
    'BOAS_VINDAS', 
    'Bem-vindo à Academia: #CURSO#', 
    'TURMA',
    '<p>Olá <strong>#NOME#</strong>,</p><p>Confirma-se a tua inscrição na turma #TURMA#.</p>'
);

INSERT INTO Modelos_Comunicacao (Codigo_Ref, Assunto, Contexto, Corpo_HTML)
VALUES (
    'LEMBRETE_INICIO', 
    'Lembrete: O teu curso começa amanhã!', 
    'TURMA',
    '<p>Olá <strong>#NOME#</strong>,</p><p>Não te esqueças que o curso #CURSO# começa amanhã, dia #DATA_INICIO#.</p>'
);

/

-- 4. Pacote de Lógica (PL/SQL)
CREATE OR REPLACE PACKAGE PKG_COMUNICACAO AS
    -- Função para substituir variáveis (O "Motor")
    FUNCTION Processar_Template(
        p_modelo_id IN NUMBER,
        p_aluno_id  IN NUMBER DEFAULT NULL,
        p_turma_id  IN NUMBER DEFAULT NULL
    ) RETURN CLOB;

    -- Função para encontrar o template correto (com fallback)
    FUNCTION Get_Modelo_Id(
        p_codigo_ref IN VARCHAR2,
        p_curso_id   IN NUMBER DEFAULT NULL
    ) RETURN NUMBER;

    -- Procedimento para Agendar um Email (Colocar na Fila)
    PROCEDURE Agendar_Email(
        p_para          IN VARCHAR2,
        p_assunto       IN VARCHAR2,
        p_corpo         IN CLOB,
        p_data_agendada IN TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        p_origem        IN VARCHAR2 DEFAULT NULL
    );

    -- Procedimento para Disparar Emails Pendentes (Será usado pela Automação)
    PROCEDURE Processar_Fila;
END PKG_COMUNICACAO;
/

CREATE OR REPLACE PACKAGE BODY PKG_COMUNICACAO AS

    FUNCTION Get_Modelo_Id(
        p_codigo_ref IN VARCHAR2,
        p_curso_id   IN NUMBER DEFAULT NULL
    ) RETURN NUMBER IS
        l_id NUMBER;
    BEGIN
        -- Tenta encontrar específico para o curso
        BEGIN
            SELECT ID_Modelo INTO l_id 
            FROM Modelos_Comunicacao 
            WHERE Codigo_Ref = p_codigo_ref 
              AND ID_Curso = p_curso_id
              AND Ativo = 'S';
            RETURN l_id;
        EXCEPTION WHEN NO_DATA_FOUND THEN
            NULL; -- Continua para o default
        END;

        -- Se não encontrou, tenta o global (ID_Curso NULL)
        BEGIN
            SELECT ID_Modelo INTO l_id 
            FROM Modelos_Comunicacao 
            WHERE Codigo_Ref = p_codigo_ref 
              AND ID_Curso IS NULL
              AND Ativo = 'S';
            RETURN l_id;
        EXCEPTION WHEN NO_DATA_FOUND THEN
            RETURN NULL; -- Não existe template
        END;
    END;

    FUNCTION Processar_Template(
        p_modelo_id IN NUMBER,
        p_aluno_id  IN NUMBER DEFAULT NULL,
        p_turma_id  IN NUMBER DEFAULT NULL
    ) RETURN CLOB IS
        l_html      CLOB;
        l_assunto   VARCHAR2(200);
        l_nome      VARCHAR2(200);
        l_curso     VARCHAR2(200);
        l_data_inicio VARCHAR2(20);
    BEGIN
        -- 1. Buscar o template bruto
        SELECT Corpo_HTML INTO l_html FROM Modelos_Comunicacao WHERE ID_Modelo = p_modelo_id;

        -- 2. Buscar dados do Aluno (se aplicável)
        IF p_aluno_id IS NOT NULL THEN
            SELECT Nome_Completo INTO l_nome FROM Entidades WHERE ID_Entidade = p_aluno_id;
            l_html := REPLACE(l_html, '#NOME#', l_nome);
        END IF;

        -- 3. Buscar dados da Turma (se aplicável)
        IF p_turma_id IS NOT NULL THEN
             -- Join simples para buscar nome do curso e data inicio
            SELECT c.Nome, t.Codigo_Turma, TO_CHAR(t.Data_Inicio, 'DD/MM/YYYY')
            INTO l_curso, l_curso, l_data_inicio -- Simplificação: usar codigo turma como "Curso" placeholder genérico
            FROM Turmas t JOIN Cursos c ON t.ID_Curso = c.ID_Curso
            WHERE t.ID_Turma = p_turma_id;
            
            l_html := REPLACE(l_html, '#CURSO#', l_curso);
            l_html := REPLACE(l_html, '#TURMA#', l_curso); -- Variação
            l_html := REPLACE(l_html, '#DATA_INICIO#', l_data_inicio);
        END IF;

        RETURN l_html;
    EXCEPTION WHEN OTHERS THEN RETURN 'Erro ao processar template: ' || SQLERRM;
    END;

    PROCEDURE Agendar_Email(
        p_para          IN VARCHAR2,
        p_assunto       IN VARCHAR2,
        p_corpo         IN CLOB,
        p_data_agendada IN TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        p_origem        IN VARCHAR2 DEFAULT NULL
    ) IS
    BEGIN
        INSERT INTO Log_Comunicacoes (Destinatario, Assunto, Corpo_HTML, Data_Agendada, Contexto_Origem)
        VALUES (p_para, p_assunto, p_corpo, p_data_agendada, p_origem);
    END;

    PROCEDURE Processar_Fila IS
    BEGIN
        FOR r IN (SELECT * FROM Log_Comunicacoes WHERE Estado = 'PENDENTE' AND Data_Agendada <= CURRENT_TIMESTAMP) LOOP
            BEGIN
                -- Envia o email usando a API nativa do APEX
                APEX_MAIL.SEND(
                    p_to   => r.Destinatario,
                    p_from => r.Remetente,
                    p_subj => r.Assunto,
                    p_body => 'Por favor ative HTML.', -- Texto simples alternativo
                    p_body_html => r.Corpo_HTML
                );
                
                -- Se não der erro, marca como enviado
                 -- IMPORTANTE: APEX_MAIL adiciona à fila interna do APEX.
                UPDATE Log_Comunicacoes SET Estado = 'ENVIADO', Data_Envio = CURRENT_TIMESTAMP WHERE ID_Log = r.ID_Log;
            EXCEPTION WHEN OTHERS THEN
                UPDATE Log_Comunicacoes SET Estado = 'ERRO', Erro_Msg = SQLERRM WHERE ID_Log = r.ID_Log;
            END;
        END LOOP;
        -- Força o envio imediato da fila interna do APEX
        APEX_MAIL.PUSH_QUEUE;
    END;
END PKG_COMUNICACAO;
/
