-- 08_Staging.sql
-- Script para criar o sistema de Staging de Importação (Expandido)
-- Versão: 8.1
-- Suporta: Género, Tipo Doc, Situação Prof, Qualificações

-- 1. Tabela de Staging (Temporária para validação)
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE Staging_Importacao';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE Staging_Importacao (
    ID_Staging       NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    Data_Upload      TIMESTAMP DEFAULT SYSTIMESTAMP,
    Utilizador       VARCHAR2(100),
    
    -- Campos "Brutos" (O que vem do Excel)
    Nome_Excel       VARCHAR2(255),
    Email_Excel      VARCHAR2(255),
    NIF_Excel        VARCHAR2(50),
    Telemovel_Excel  VARCHAR2(50),
    
    Genero_Excel     VARCHAR2(50),  -- Lookup: Tipos_Genero
    Tipo_Doc_Excel   VARCHAR2(50),  -- Lookup: Tipos_Doc_Identificacao
    Num_Doc_Excel    VARCHAR2(50),  -- Texto Livre
    Sit_Prof_Excel   VARCHAR2(100), -- Lookup: Tipos_Situacao_Profissional
    Qualificacao_Excel VARCHAR2(100), -- Lookup: Tipos_De_Qualificacao
    
    Curso_Excel      VARCHAR2(255), -- Lookup: Cursos
    Data_Interesse_Excel VARCHAR2(50), -- Se vazio -> Hoje
    Diagnostico_Excel VARCHAR2(4000), -- [NOVO] Respostas ao Diagnóstico (Texto/JSON)
    
    -- Campos de Validação e Mapeamento
    Linha_Valida     CHAR(1) DEFAULT 'N',     
    Mensagem_Erro    VARCHAR2(4000),          
    
    -- IDs Resolvidos (Preenchidos pelo PL/SQL)
    ID_Curso_Mapeado NUMBER,
    ID_Genero_Mapeado NUMBER,
    ID_Tipo_Doc_Mapeado NUMBER,
    ID_Sit_Prof_Mapeado NUMBER,
    ID_Qualificacao_Mapeado NUMBER,
    
    ID_Entidade_Existente NUMBER, -- Se já existir pessoa
    Data_Interesse_Final DATE     -- Data tratada
);

-- 2. Package de Lógica de Importação
create or replace PACKAGE PKG_IMPORTACAO AS
    PROCEDURE Processar_Staging;
    PROCEDURE Validar_Linha(p_id_staging NUMBER);
END PKG_IMPORTACAO;
/

create or replace PACKAGE BODY PKG_IMPORTACAO AS

    -- Função auxiliar para tentar parsear datas
    FUNCTION Try_Parse_Date(p_str VARCHAR2) RETURN DATE IS
    BEGIN
        IF p_str IS NULL THEN RETURN TRUNC(SYSDATE); END IF; -- Regra: Vazio = Hoje
        BEGIN
            RETURN TO_DATE(p_str, 'YYYY-MM-DD'); -- Formato ISO Preferido do Excel
        EXCEPTION WHEN OTHERS THEN
            BEGIN
                RETURN TO_DATE(p_str, 'DD/MM/YYYY'); -- Formato PT Comum
            EXCEPTION WHEN OTHERS THEN
                RETURN NULL; -- Data Inválida
            END;
        END;
    END;

    PROCEDURE Validar_Linha(p_id_staging NUMBER) IS
        r_line Staging_Importacao%ROWTYPE;
        v_erro VARCHAR2(4000) := '';
        
        -- Variáveis temporárias para Lookups
        v_val_id NUMBER;
    BEGIN
        SELECT * INTO r_line FROM Staging_Importacao WHERE ID_Staging = p_id_staging;
        
        -- A. Email (Obrigatório)
        IF r_line.Email_Excel IS NULL THEN v_erro := v_erro || 'Email obrigatório; '; END IF;

        -- B. Curso (Obrigatório)
        BEGIN
            SELECT ID_Curso INTO r_line.ID_Curso_Mapeado FROM Cursos WHERE upper(Nome) = upper(trim(r_line.Curso_Excel));
        EXCEPTION WHEN NO_DATA_FOUND THEN
            v_erro := v_erro || 'Curso "'||r_line.Curso_Excel||'" não encontrado; ';
        END;

        -- C. Género (Opcional)
        IF r_line.Genero_Excel IS NOT NULL THEN
            BEGIN
                SELECT ID_Genero INTO r_line.ID_Genero_Mapeado FROM Tipos_Genero 
                WHERE upper(Descricao) = upper(trim(r_line.Genero_Excel)) OR upper(Codigo) = upper(trim(r_line.Genero_Excel));
            EXCEPTION WHEN NO_DATA_FOUND THEN v_erro := v_erro || 'Género inválido; ';
            END;
        END IF;

        -- D. Tipo Documento (Opcional)
        IF r_line.Tipo_Doc_Excel IS NOT NULL THEN
            BEGIN
                SELECT ID_Tipo_Doc INTO r_line.ID_Tipo_Doc_Mapeado FROM Tipos_Doc_Identificacao 
                WHERE upper(Descricao) = upper(trim(r_line.Tipo_Doc_Excel)) OR upper(Codigo) = upper(trim(r_line.Tipo_Doc_Excel));
            EXCEPTION WHEN NO_DATA_FOUND THEN v_erro := v_erro || 'Tipo Doc inválido; ';
            END;
        END IF;

        -- E. Situação Profissional (Opcional)
        IF r_line.Sit_Prof_Excel IS NOT NULL THEN
            BEGIN
                SELECT ID_Situacao_Prof INTO r_line.ID_Sit_Prof_Mapeado FROM Tipos_Situacao_Profissional
                WHERE upper(Descricao) = upper(trim(r_line.Sit_Prof_Excel)) OR upper(Codigo) = upper(trim(r_line.Sit_Prof_Excel));
            EXCEPTION WHEN NO_DATA_FOUND THEN v_erro := v_erro || 'Sit. Prof. inválida; ';
            END;
        END IF;

        -- F. Qualificações (Opcional)
        IF r_line.Qualificacao_Excel IS NOT NULL THEN
            BEGIN
                SELECT ID_Qualificacao INTO r_line.ID_Qualificacao_Mapeado FROM Tipos_De_Qualificacao
                WHERE upper(Descricao) = upper(trim(r_line.Qualificacao_Excel)) OR upper(Codigo) = upper(trim(r_line.Qualificacao_Excel));
            EXCEPTION WHEN NO_DATA_FOUND THEN v_erro := v_erro || 'Qualificação inválida; ';
            END;
        END IF;

        -- G. Data Interesse (Regra: Hoje se vazio)
        r_line.Data_Interesse_Final := Try_Parse_Date(r_line.Data_Interesse_Excel);
        IF r_line.Data_Interesse_Final IS NULL THEN
            v_erro := v_erro || 'Data Inválida; ';
        END IF;

        -- H. Verificar Duplicados (Entidade)
        BEGIN
            SELECT ID_Entidade INTO r_line.ID_Entidade_Existente FROM Entidades WHERE upper(Email) = upper(trim(r_line.Email_Excel));
        EXCEPTION WHEN NO_DATA_FOUND THEN r_line.ID_Entidade_Existente := NULL;
        END;

        -- Atualizar Linha
        UPDATE Staging_Importacao
        SET ID_Curso_Mapeado = r_line.ID_Curso_Mapeado,
            ID_Genero_Mapeado = r_line.ID_Genero_Mapeado,
            ID_Tipo_Doc_Mapeado = r_line.ID_Tipo_Doc_Mapeado,
            ID_Sit_Prof_Mapeado = r_line.ID_Sit_Prof_Mapeado,
            ID_Qualificacao_Mapeado = r_line.ID_Qualificacao_Mapeado,
            ID_Entidade_Existente = r_line.ID_Entidade_Existente,
            Data_Interesse_Final = r_line.Data_Interesse_Final,
            Mensagem_Erro = v_erro,
            Linha_Valida = CASE WHEN v_erro IS NULL THEN 'S' ELSE 'N' END
        WHERE ID_Staging = p_id_staging;
        
    END Validar_Linha;

    PROCEDURE Processar_Staging IS
    BEGIN
        -- 1. Revalidar tudo
        FOR r IN (SELECT ID_Staging FROM Staging_Importacao) LOOP
            Validar_Linha(r.ID_Staging);
        END LOOP;

        -- 2. Inserir/Atualizar Entidades e Matrículas (Apenas válidos)
        FOR r IN (SELECT * FROM Staging_Importacao WHERE Linha_Valida = 'S') LOOP
            
            -- A. Upsert Entidade
            IF r.ID_Entidade_Existente IS NULL THEN
                INSERT INTO Entidades (
                    Nome_Completo, Email, Nif, Telemovel, 
                    ID_Genero, ID_Tipo_Doc, Num_Doc_Identificacao, 
                    ID_Situacao_Prof, ID_Qualificacao, Origem_Registo
                )
                VALUES (
                    r.Nome_Excel, r.Email_Excel, r.NIF_Excel, r.Telemovel_Excel, 
                    r.ID_Genero_Mapeado, r.ID_Tipo_Doc_Mapeado, r.Num_Doc_Excel, 
                    r.ID_Sit_Prof_Mapeado, r.ID_Qualificacao_Mapeado, 'IMPORT'
                )
                RETURNING ID_Entidade INTO r.ID_Entidade_Existente;
            ELSE
                -- Update (Exemplo: preencher campos em falta se vierem no excel)
                UPDATE Entidades SET 
                    Nif = COALESCE(Nif, r.NIF_Excel),
                    ID_Situacao_Prof = COALESCE(ID_Situacao_Prof, r.ID_Sit_Prof_Mapeado)
                WHERE ID_Entidade = r.ID_Entidade_Existente;
            END IF;

            -- B. Criar Inscrição
            INSERT INTO Inscricoes (ID_Curso, ID_Entidade, Data_Registo, Origem, Respostas_Diagnostico)
            SELECT r.ID_Curso_Mapeado, r.ID_Entidade_Existente, r.Data_Interesse_Final, 'IMPORT', r.Diagnostico_Excel
            FROM DUAL
            WHERE NOT EXISTS (SELECT 1 FROM Inscricoes WHERE ID_Entidade = r.ID_Entidade_Existente AND ID_Curso = r.ID_Curso_Mapeado);

            -- C. Limpar OK
            DELETE FROM Staging_Importacao WHERE ID_Staging = r.ID_Staging;
            
        END LOOP;
    END Processar_Staging;

END PKG_IMPORTACAO;
/
