-- 01_lookup_tables.sql
-- SGUF v9 - Fase 1: Tabelas de Domínio (Lookups)
-- Todas as tabelas visíveis têm nomenclatura em Português (PT-PT)

-- 19. Tipos_Area_Competencia
CREATE TABLE Tipos_Area_Competencia (
    ID_Area_Competencia NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    Codigo VARCHAR2(50) NOT NULL UNIQUE,
    Descricao VARCHAR2(200) NOT NULL,
    Ordem NUMBER,
    Ativo CHAR(1) DEFAULT 'S' CHECK (Ativo IN ('S','N'))
);

-- 20. Tipos_Nivel_Proficiencia
CREATE TABLE Tipos_Nivel_Proficiencia (
    ID_Nivel_Proficiencia NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    Codigo VARCHAR2(50) NOT NULL UNIQUE,
    Descricao VARCHAR2(200) NOT NULL,
    Ordem NUMBER
);

-- 21. Tipos_Estado_Curso
CREATE TABLE Tipos_Estado_Curso (
    ID_Estado_Curso NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    Codigo VARCHAR2(50) NOT NULL UNIQUE,
    Descricao VARCHAR2(200) NOT NULL
);

-- 22. Tipos_Genero
CREATE TABLE Tipos_Genero (
    ID_Genero NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    Codigo VARCHAR2(20) NOT NULL UNIQUE,
    Descricao VARCHAR2(100) NOT NULL
);

-- 23. Tipos_Doc_Identificacao
CREATE TABLE Tipos_Doc_Identificacao (
    ID_Tipo_Doc NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    Codigo VARCHAR2(20) NOT NULL UNIQUE,
    Descricao VARCHAR2(100) NOT NULL
);

-- 24. Tipos_Situacao_Profissional
CREATE TABLE Tipos_Situacao_Profissional (
    ID_Situacao_Prof NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    Codigo VARCHAR2(50) NOT NULL UNIQUE,
    Descricao VARCHAR2(200) NOT NULL
);

-- 25. Tipos_De_Qualificacao
CREATE TABLE Tipos_De_Qualificacao (
    ID_Qualificacao NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    Codigo VARCHAR2(50) NOT NULL UNIQUE,
    Descricao VARCHAR2(200) NOT NULL,
    Ordem NUMBER
);

-- 26. Tipos_Estado_Turma
CREATE TABLE Tipos_Estado_Turma (
    ID_Estado_Turma NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    Codigo VARCHAR2(50) NOT NULL UNIQUE,
    Descricao VARCHAR2(200) NOT NULL
);

-- 27. Tipos_Estado_Matricula
CREATE TABLE Tipos_Estado_Matricula (
    ID_Estado_Matricula NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    Codigo VARCHAR2(50) NOT NULL UNIQUE,
    Descricao VARCHAR2(200) NOT NULL
);

-- 28. Tipos_Estado_Presenca
CREATE TABLE Tipos_Estado_Presenca (
    ID_Estado_Presenca NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    Codigo VARCHAR2(20) NOT NULL UNIQUE,
    Descricao VARCHAR2(100) NOT NULL,
    Considera_Presenca CHAR(1) DEFAULT 'N' CHECK (Considera_Presenca IN ('S','N'))
);

-- 29. Tipos_Nivel_Experiencia
CREATE TABLE Tipos_Nivel_Experiencia (
    ID_Nivel_Experiencia NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    Codigo VARCHAR2(50) NOT NULL UNIQUE,
    Descricao VARCHAR2(200) NOT NULL
);

-- 30. Tipos_Equipamento
CREATE TABLE Tipos_Equipamento (
    ID_Tipo_Equipamento NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    Codigo VARCHAR2(50) NOT NULL UNIQUE,
    Descricao VARCHAR2(200) NOT NULL
);

-- 31. Tipos_Plano_DDF
CREATE TABLE Tipos_Plano_DDF (
    ID_Tipo_Plano NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    Codigo VARCHAR2(50) NOT NULL UNIQUE,
    Descricao VARCHAR2(200) NOT NULL
);

-- 32. Tipos_Documento_Dossier
CREATE TABLE Tipos_Documento_Dossier (
    ID_Tipo_Doc NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    Codigo VARCHAR2(50) NOT NULL UNIQUE,
    Descricao VARCHAR2(200) NOT NULL,
    Obrigatorio CHAR(1) DEFAULT 'N' CHECK (Obrigatorio IN ('S','N'))
);

-- 33. Tipos_Notificacao
CREATE TABLE Tipos_Notificacao (
    ID_Tipo_Notificacao NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    Codigo VARCHAR2(20) NOT NULL UNIQUE,
    Descricao VARCHAR2(200) NOT NULL
);

-- ==========================================
-- SEED DATA (Lookups)
-- ==========================================

INSERT INTO Tipos_Area_Competencia (Codigo, Descricao, Ordem) VALUES ('INFO', 'Informação e Literacia de Dados', 1);
INSERT INTO Tipos_Area_Competencia (Codigo, Descricao, Ordem) VALUES ('COM', 'Comunicação e Colaboração', 2);
INSERT INTO Tipos_Area_Competencia (Codigo, Descricao, Ordem) VALUES ('CRIACAO', 'Criação de Conteúdos Digitais', 3);
INSERT INTO Tipos_Area_Competencia (Codigo, Descricao, Ordem) VALUES ('SEG', 'Segurança', 4);
INSERT INTO Tipos_Area_Competencia (Codigo, Descricao, Ordem) VALUES ('RES_PROBLEMAS', 'Resolução de Problemas', 5);

INSERT INTO Tipos_Nivel_Proficiencia (Codigo, Descricao, Ordem) VALUES ('BASICO', 'Básico', 1);
INSERT INTO Tipos_Nivel_Proficiencia (Codigo, Descricao, Ordem) VALUES ('INTERMEDIO', 'Intermédio', 2);
INSERT INTO Tipos_Nivel_Proficiencia (Codigo, Descricao, Ordem) VALUES ('AVANCADO', 'Avançado', 3);

INSERT INTO Tipos_Estado_Curso (Codigo, Descricao) VALUES ('RASCUNHO', 'Rascunho');
INSERT INTO Tipos_Estado_Curso (Codigo, Descricao) VALUES ('ATIVO', 'Ativo');
INSERT INTO Tipos_Estado_Curso (Codigo, Descricao) VALUES ('INATIVO', 'Inativo');
INSERT INTO Tipos_Estado_Curso (Codigo, Descricao) VALUES ('ARQUIVADO', 'Arquivado');

INSERT INTO Tipos_Genero (Codigo, Descricao) VALUES ('M', 'Masculino');
INSERT INTO Tipos_Genero (Codigo, Descricao) VALUES ('F', 'Feminino');
INSERT INTO Tipos_Genero (Codigo, Descricao) VALUES ('O', 'Outro');
INSERT INTO Tipos_Genero (Codigo, Descricao) VALUES ('NR', 'Não Responde');

INSERT INTO Tipos_Doc_Identificacao (Codigo, Descricao) VALUES ('CC', 'Cartão de Cidadão');
INSERT INTO Tipos_Doc_Identificacao (Codigo, Descricao) VALUES ('PASSAPORTE', 'Passaporte');
INSERT INTO Tipos_Doc_Identificacao (Codigo, Descricao) VALUES ('AR', 'Autorização de Residência');
INSERT INTO Tipos_Doc_Identificacao (Codigo, Descricao) VALUES ('OUTRO', 'Outro');

INSERT INTO Tipos_Situacao_Profissional (Codigo, Descricao) VALUES ('EMPREGADO', 'Empregado/a');
INSERT INTO Tipos_Situacao_Profissional (Codigo, Descricao) VALUES ('DESEMPREGADO', 'Desempregado/a');
INSERT INTO Tipos_Situacao_Profissional (Codigo, Descricao) VALUES ('ESTUDANTE', 'Estudante');
INSERT INTO Tipos_Situacao_Profissional (Codigo, Descricao) VALUES ('OUTRA', 'Outra situação');

INSERT INTO Tipos_De_Qualificacao (Codigo, Descricao, Ordem) VALUES ('BASICO', 'Ensino Básico', 1);
INSERT INTO Tipos_De_Qualificacao (Codigo, Descricao, Ordem) VALUES ('SECUNDARIO', 'Ensino Secundário', 2);
INSERT INTO Tipos_De_Qualificacao (Codigo, Descricao, Ordem) VALUES ('LICENCIATURA', 'Licenciatura', 3);
INSERT INTO Tipos_De_Qualificacao (Codigo, Descricao, Ordem) VALUES ('MESTRADO', 'Mestrado', 4);
INSERT INTO Tipos_De_Qualificacao (Codigo, Descricao, Ordem) VALUES ('DOUTORAMENTO', 'Doutoramento', 5);

INSERT INTO Tipos_Estado_Turma (Codigo, Descricao) VALUES ('PLANEADA', 'Planeada');
INSERT INTO Tipos_Estado_Turma (Codigo, Descricao) VALUES ('CONFIRMADA', 'Confirmada');
INSERT INTO Tipos_Estado_Turma (Codigo, Descricao) VALUES ('DECORRER', 'A Decorrer');
INSERT INTO Tipos_Estado_Turma (Codigo, Descricao) VALUES ('TERMINADA', 'Terminada');
INSERT INTO Tipos_Estado_Turma (Codigo, Descricao) VALUES ('CANCELADA', 'Cancelada');

INSERT INTO Tipos_Estado_Matricula (Codigo, Descricao) VALUES ('INSCRITO', 'Inscrito');
INSERT INTO Tipos_Estado_Matricula (Codigo, Descricao) VALUES ('FREQUENTAR', 'A Frequentar');
INSERT INTO Tipos_Estado_Matricula (Codigo, Descricao) VALUES ('CONCLUIDO', 'Concluído');
INSERT INTO Tipos_Estado_Matricula (Codigo, Descricao) VALUES ('DESISTIU', 'Desistiu');
INSERT INTO Tipos_Estado_Matricula (Codigo, Descricao) VALUES ('REPROVADO', 'Reprovado');

-- Lacuna Resolvida: Adicionado estado CV (Convocado) com Considera_Presenca = 'N'
INSERT INTO Tipos_Estado_Presenca (Codigo, Descricao, Considera_Presenca) VALUES ('P', 'Presente', 'S');
INSERT INTO Tipos_Estado_Presenca (Codigo, Descricao, Considera_Presenca) VALUES ('F', 'Faltou', 'N');
INSERT INTO Tipos_Estado_Presenca (Codigo, Descricao, Considera_Presenca) VALUES ('FJ', 'Falta Justificada', 'N');
INSERT INTO Tipos_Estado_Presenca (Codigo, Descricao, Considera_Presenca) VALUES ('CV', 'Convocado', 'N'); 

INSERT INTO Tipos_Nivel_Experiencia (Codigo, Descricao) VALUES ('INICIANTE', 'Iniciante');
INSERT INTO Tipos_Nivel_Experiencia (Codigo, Descricao) VALUES ('INTERMEDIO', 'Intermédio');
INSERT INTO Tipos_Nivel_Experiencia (Codigo, Descricao) VALUES ('AVANCADO', 'Avançado');

INSERT INTO Tipos_Equipamento (Codigo, Descricao) VALUES ('PC', 'Computador Portátil / PC');
INSERT INTO Tipos_Equipamento (Codigo, Descricao) VALUES ('ROUTER', 'Router 4G/5G');
INSERT INTO Tipos_Equipamento (Codigo, Descricao) VALUES ('TABLET', 'Tablet');

INSERT INTO Tipos_Plano_DDF (Codigo, Descricao) VALUES ('INTERNA', 'Formação Interna');
INSERT INTO Tipos_Plano_DDF (Codigo, Descricao) VALUES ('EXTERNA', 'Formação Externa');

INSERT INTO Tipos_Documento_Dossier (Codigo, Descricao, Obrigatorio) VALUES ('SUMARIO', 'Sumário da Sessão', 'S');
INSERT INTO Tipos_Documento_Dossier (Codigo, Descricao, Obrigatorio) VALUES ('PAUTA', 'Pauta de Avaliação', 'S');
INSERT INTO Tipos_Documento_Dossier (Codigo, Descricao, Obrigatorio) VALUES ('QUEST_SAT', 'Questionário de Satisfação', 'N');

INSERT INTO Tipos_Notificacao (Codigo, Descricao) VALUES ('EMAIL', 'Email');
INSERT INTO Tipos_Notificacao (Codigo, Descricao) VALUES ('SMS', 'SMS');

COMMIT;
