-- 02_core_catalog.sql
-- SGUF v9 - Fase 2: Catálogo Core
-- 1. Programas
CREATE TABLE Programas (
    ID_Programa NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    Codigo VARCHAR2(50) NOT NULL UNIQUE,
    Nome VARCHAR2(200) NOT NULL,
    Descricao VARCHAR2(4000),
    Ativo CHAR(1) DEFAULT 'S' CHECK (Ativo IN ('S','N'))
);

-- 2. Cursos
CREATE TABLE Cursos (
    ID_Curso NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    ID_Programa NUMBER,
    Codigo VARCHAR2(50) UNIQUE,
    Nome VARCHAR2(255) NOT NULL,
    Nome_Curso_SIGO VARCHAR2(100),
    Carga_Horaria NUMBER,
    Modalidade VARCHAR2(50),
    Forma_Organizacao VARCHAR2(50),
    Publico_Alvo VARCHAR2(4000),
    Objetivos_Gerais CLOB,
    Objetivos_Especificos CLOB,
    Conteudos_Programaticos CLOB,
    Metodologia_Avaliacao CLOB,
    Metodologia_Formacao CLOB,
    Recursos_Didaticos CLOB,
    URL_Manual_Digital VARCHAR2(500),
    ID_Estado_Curso NUMBER,
    CONSTRAINT FK_Cursos_Programas FOREIGN KEY (ID_Programa) REFERENCES Programas(ID_Programa),
    CONSTRAINT FK_Cursos_Estado FOREIGN KEY (ID_Estado_Curso) REFERENCES Tipos_Estado_Curso(ID_Estado_Curso)
);

-- 3. Modulos
CREATE TABLE Modulos (
    ID_Modulo NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    ID_Curso NUMBER,
    Nome VARCHAR2(255) NOT NULL,
    Ordem NUMBER,
    Carga_Horaria NUMBER,
    Tipo_Avaliacao VARCHAR2(20) CHECK (Tipo_Avaliacao IN ('QUANTITATIVA', 'QUALITATIVA', 'NENHUMA')),
    CONSTRAINT FK_Modulos_Cursos FOREIGN KEY (ID_Curso) REFERENCES Cursos(ID_Curso)
);

-- 4. Catalogo_Competencias
CREATE TABLE Catalogo_Competencias (
    ID_Competencia NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    Codigo VARCHAR2(50) UNIQUE,
    Nome VARCHAR2(255) NOT NULL,
    Descricao VARCHAR2(4000),
    ID_Area_Competencia NUMBER,
    ID_Nivel_Proficiencia NUMBER,
    Ativo CHAR(1) DEFAULT 'S' CHECK (Ativo IN ('S','N')),
    CONSTRAINT FK_Competencia_Area FOREIGN KEY (ID_Area_Competencia) REFERENCES Tipos_Area_Competencia(ID_Area_Competencia),
    CONSTRAINT FK_Competencia_Nivel FOREIGN KEY (ID_Nivel_Proficiencia) REFERENCES Tipos_Nivel_Proficiencia(ID_Nivel_Proficiencia)
);

-- 4a. Modulo_Competencias
CREATE TABLE Modulo_Competencias (
    ID_Associacao NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    ID_Modulo NUMBER,
    ID_Competencia NUMBER,
    Obrigatorio CHAR(1) DEFAULT 'S' CHECK (Obrigatorio IN ('S','N')),
    CONSTRAINT FK_Assoc_Modulo FOREIGN KEY (ID_Modulo) REFERENCES Modulos(ID_Modulo),
    CONSTRAINT FK_Assoc_Competencia FOREIGN KEY (ID_Competencia) REFERENCES Catalogo_Competencias(ID_Competencia)
);

-- 4b. Catalogo_Medalhas
CREATE TABLE Catalogo_Medalhas (
    ID_Medalha NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    Codigo VARCHAR2(50) UNIQUE,
    Nome VARCHAR2(255) NOT NULL,
    Descricao VARCHAR2(4000),
    URL_Medalha_Digital VARCHAR2(500),
    URL_Imagem VARCHAR2(500),
    URL_Claim_Badge VARCHAR2(500),
    Ativo CHAR(1) DEFAULT 'S' CHECK (Ativo IN ('S','N'))
);

-- 4c. Competencia_Medalhas
CREATE TABLE Competencia_Medalhas (
    ID_Associacao NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    ID_Competencia NUMBER,
    ID_Medalha NUMBER,
    CONSTRAINT FK_AssocMed_Competencia FOREIGN KEY (ID_Competencia) REFERENCES Catalogo_Competencias(ID_Competencia),
    CONSTRAINT FK_AssocMed_Medalha FOREIGN KEY (ID_Medalha) REFERENCES Catalogo_Medalhas(ID_Medalha)
);
