-- 03_people.sql
-- SGUF v9 - Fase 3: Pessoas e Entidades

-- 5. Entidades
CREATE TABLE Entidades (
    ID_Entidade NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    NIF VARCHAR2(20) UNIQUE,
    Email VARCHAR2(255) UNIQUE,
    Nome_Completo VARCHAR2(255) NOT NULL,
    Telemovel VARCHAR2(50),
    Data_Nascimento DATE,
    ID_Genero NUMBER,
    Naturalidade VARCHAR2(100),
    Nacionalidade VARCHAR2(100),
    ID_Tipo_Doc NUMBER,
    Num_Doc_Identificacao VARCHAR2(50),
    Validade_Doc DATE,
    Morada VARCHAR2(255),
    Codigo_Postal VARCHAR2(20),
    Localidade VARCHAR2(100),
    ID_Situacao_Prof NUMBER,
    Profissao VARCHAR2(100),
    Entidade_Empregadora VARCHAR2(200),
    Morada_Prof VARCHAR2(255),
    Codigo_Postal_Prof VARCHAR2(20),
    Localidade_Prof VARCHAR2(100),
    Telemovel_Prof VARCHAR2(50),
    URL_CV VARCHAR2(500),
    ID_Qualificacao NUMBER,
    Consentimento_RGPD CHAR(1) DEFAULT 'N' CHECK (Consentimento_RGPD IN ('S','N')),
    Aceita_Newsletter CHAR(1) DEFAULT 'N' CHECK (Aceita_Newsletter IN ('S','N')), -- [NOVO v9] Gap SharePoint
    Observacoes CLOB,
    Data_Criacao DATE DEFAULT SYSDATE,
    Ativo CHAR(1) DEFAULT 'S' CHECK (Ativo IN ('S','N')),
    Origem_Registo VARCHAR2(50) DEFAULT 'MANUAL',
    CONSTRAINT FK_Entidade_Genero FOREIGN KEY (ID_Genero) REFERENCES Tipos_Genero(ID_Genero),
    CONSTRAINT FK_Entidade_TipoDoc FOREIGN KEY (ID_Tipo_Doc) REFERENCES Tipos_Doc_Identificacao(ID_Tipo_Doc),
    CONSTRAINT FK_Entidade_SitProf FOREIGN KEY (ID_Situacao_Prof) REFERENCES Tipos_Situacao_Profissional(ID_Situacao_Prof),
    CONSTRAINT FK_Entidade_Qualificacao FOREIGN KEY (ID_Qualificacao) REFERENCES Tipos_De_Qualificacao(ID_Qualificacao)
);

-- 6. Papeis_Entidade
CREATE TABLE Papeis_Entidade (
    ID_Papel NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    ID_Entidade NUMBER,
    Codigo_Papel VARCHAR2(20) CHECK (Codigo_Papel IN ('ADMIN', 'FORMADOR', 'FORMANDO', 'COORDENADOR')),
    CONSTRAINT FK_Papeis_Entidade FOREIGN KEY (ID_Entidade) REFERENCES Entidades(ID_Entidade)
);

-- 6a. Listas_Mailing
CREATE TABLE Listas_Mailing (
    ID_Lista NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    Nome_Lista VARCHAR2(100) NOT NULL,
    Descricao VARCHAR2(255),
    Ativo CHAR(1) DEFAULT 'S' CHECK (Ativo IN ('S','N'))
);

-- 6b. Entidade_Listas
CREATE TABLE Entidade_Listas (
    ID_Entidade NUMBER,
    ID_Lista NUMBER,
    Data_Associacao DATE DEFAULT SYSDATE,
    Created_By VARCHAR2(100),
    PRIMARY KEY (ID_Entidade, ID_Lista),
    CONSTRAINT FK_EntLista_Entidade FOREIGN KEY (ID_Entidade) REFERENCES Entidades(ID_Entidade),
    CONSTRAINT FK_EntLista_Lista FOREIGN KEY (ID_Lista) REFERENCES Listas_Mailing(ID_Lista)
);

-- 34. Locais
CREATE TABLE Locais (
    ID_Local NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    Codigo VARCHAR2(50) UNIQUE,
    Nome VARCHAR2(200) NOT NULL,
    Morada VARCHAR2(500),
    Capacidade NUMBER,
    Ativo CHAR(1) DEFAULT 'S' CHECK (Ativo IN ('S','N'))
);
