-- 04_ops_formativa.sql
-- SGUF v9 - Fase 4: Operação Formativa

-- 7. Turmas
CREATE TABLE Turmas (
    ID_Turma NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    ID_Curso NUMBER,
    Codigo_Turma VARCHAR2(100) UNIQUE,
    Nome_Turma VARCHAR2(200),
    ID_Estado_Turma NUMBER,
    Data_Inicio DATE,
    Data_Fim DATE,
    ID_Local NUMBER,
    Horario_Descritivo VARCHAR2(500),
    ID_Coordenador NUMBER,
    Vagas NUMBER,
    Num_Informacao VARCHAR2(100),
    Num_Informacao_Mae VARCHAR2(100),
    Cod_Acao_SIGO VARCHAR2(100),
    ID_Tipo_Plano NUMBER,
    Avaliacao_Ativa CHAR(1) DEFAULT 'S' CHECK (Avaliacao_Ativa IN ('S','N')),
    Observacoes CLOB,
    CONSTRAINT FK_Turmas_Curso FOREIGN KEY (ID_Curso) REFERENCES Cursos(ID_Curso),
    CONSTRAINT FK_Turmas_Estado FOREIGN KEY (ID_Estado_Turma) REFERENCES Tipos_Estado_Turma(ID_Estado_Turma),
    CONSTRAINT FK_Turmas_Local FOREIGN KEY (ID_Local) REFERENCES Locais(ID_Local),
    CONSTRAINT FK_Turmas_Coordenador FOREIGN KEY (ID_Coordenador) REFERENCES Entidades(ID_Entidade),
    CONSTRAINT FK_Turmas_TipoPlano FOREIGN KEY (ID_Tipo_Plano) REFERENCES Tipos_Plano_DDF(ID_Tipo_Plano)
);

-- 8. Equipa_Formativa
CREATE TABLE Equipa_Formativa (
    ID_Turma NUMBER,
    ID_Formador NUMBER,
    Principal CHAR(1) DEFAULT 'N' CHECK (Principal IN ('S','N')),
    PRIMARY KEY (ID_Turma, ID_Formador),
    CONSTRAINT FK_Equipa_Turma FOREIGN KEY (ID_Turma) REFERENCES Turmas(ID_Turma),
    CONSTRAINT FK_Equipa_Formador FOREIGN KEY (ID_Formador) REFERENCES Entidades(ID_Entidade)
);

-- 9. Turma_Medalhas_Elegiveis
CREATE TABLE Turma_Medalhas_Elegiveis (
    ID_Associacao NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    ID_Turma NUMBER,
    ID_Medalha NUMBER,
    Selecionado_Por VARCHAR2(255),
    CONSTRAINT FK_TurmaMed_Turma FOREIGN KEY (ID_Turma) REFERENCES Turmas(ID_Turma),
    CONSTRAINT FK_TurmaMed_Medalha FOREIGN KEY (ID_Medalha) REFERENCES Catalogo_Medalhas(ID_Medalha)
);

-- 9a. Inscricoes
CREATE TABLE Inscricoes (
    ID_Inscricao NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    ID_Curso NUMBER,
    ID_Entidade NUMBER,
    ID_Turma_Preferencia NUMBER,
    Data_Registo DATE DEFAULT SYSDATE,
    Origem VARCHAR2(50),
    Respostas_Diagnostico CLOB,
    Estado_Inscricao VARCHAR2(50) DEFAULT 'PENDENTE',
    Observacoes VARCHAR2(4000),
    CONSTRAINT FK_Inscricoes_Curso FOREIGN KEY (ID_Curso) REFERENCES Cursos(ID_Curso),
    CONSTRAINT FK_Inscricoes_Entidade FOREIGN KEY (ID_Entidade) REFERENCES Entidades(ID_Entidade),
    CONSTRAINT FK_Inscricoes_Turma FOREIGN KEY (ID_Turma_Preferencia) REFERENCES Turmas(ID_Turma)
);

-- 10. Matriculas
CREATE TABLE Matriculas (
    ID_Matricula NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    ID_Turma NUMBER,
    ID_Aluno NUMBER,
    Token_Acesso VARCHAR2(20) UNIQUE,
    ID_Estado_Matricula NUMBER,
    Data_Inscricao DATE DEFAULT SYSDATE,
    Diagnostico_Respostas CLOB,
    Data_Conclusao DATE,
    Classificacao_Final VARCHAR2(50),
    Total_Horas NUMBER,
    Avaliacao_Curso NUMBER,
    Comentario_Aluno CLOB,
    Obs_SIGO VARCHAR2(4000),
    ID_Nivel_Experiencia NUMBER,
    Codigo_Matricula VARCHAR2(20), -- [NOVO v9] Gap SharePoint
    CONSTRAINT FK_Matriculas_Turma FOREIGN KEY (ID_Turma) REFERENCES Turmas(ID_Turma),
    CONSTRAINT FK_Matriculas_Aluno FOREIGN KEY (ID_Aluno) REFERENCES Entidades(ID_Entidade),
    CONSTRAINT FK_Matriculas_Estado FOREIGN KEY (ID_Estado_Matricula) REFERENCES Tipos_Estado_Matricula(ID_Estado_Matricula),
    CONSTRAINT FK_Matriculas_NivExp FOREIGN KEY (ID_Nivel_Experiencia) REFERENCES Tipos_Nivel_Experiencia(ID_Nivel_Experiencia)
);

-- Trigger para [NOVO v9] Codigo_Matricula Automático
-- Equivalente ao Fluxo A do Power Automate
CREATE OR REPLACE TRIGGER TRG_MATRICULAS_CODIGO
AFTER INSERT ON Matriculas
FOR EACH ROW
BEGIN
    UPDATE Matriculas
    SET Codigo_Matricula = 'INSC' || LPAD(:NEW.ID_Matricula, 4, '0')
    WHERE ID_Matricula = :NEW.ID_Matricula;
END;
/

-- 10. Sessoes
CREATE TABLE Sessoes (
    ID_Sessao NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    ID_Turma NUMBER,
    Nome VARCHAR2(200),
    Data_Sessao DATE,
    Hora_Inicio VARCHAR2(5),
    Hora_Fim VARCHAR2(5),
    Duracao_Horas NUMBER,
    Sumario CLOB,
    ID_Formador NUMBER,
    URL_Recursos VARCHAR2(1000),
    CONSTRAINT FK_Sessoes_Turma FOREIGN KEY (ID_Turma) REFERENCES Turmas(ID_Turma),
    CONSTRAINT FK_Sessoes_Formador FOREIGN KEY (ID_Formador) REFERENCES Entidades(ID_Entidade)
);

-- 11. Presencas
CREATE TABLE Presencas (
    ID_Presenca NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    ID_Sessao NUMBER,
    ID_Matricula NUMBER,
    ID_Estado_Presenca NUMBER,
    Horas_Assistidas NUMBER,
    Data_Registo TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_Presencas_Sessao FOREIGN KEY (ID_Sessao) REFERENCES Sessoes(ID_Sessao),
    CONSTRAINT FK_Presencas_Matricula FOREIGN KEY (ID_Matricula) REFERENCES Matriculas(ID_Matricula),
    CONSTRAINT FK_Presencas_Estado FOREIGN KEY (ID_Estado_Presenca) REFERENCES Tipos_Estado_Presenca(ID_Estado_Presenca)
);
