-- 06_comunicacao.sql
-- SGUF v9 - Fase 6: Sistema de Automação de Comunicações

-- 1. Modelos de Comunicação (Templates)
CREATE TABLE Modelos_Comunicacao (
    ID_Modelo NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    Codigo_Ref VARCHAR2(50) NOT NULL,
    Assunto VARCHAR2(200) NOT NULL,
    Corpo_HTML CLOB,
    Contexto VARCHAR2(20) DEFAULT 'GERAL' CHECK (Contexto IN ('TURMA', 'ALUNO', 'GERAL')),
    ID_Curso NUMBER,
    Ativo CHAR(1) DEFAULT 'S' CHECK (Ativo IN ('S','N')),
    CONSTRAINT UK_Modelo_Ref_Curso UNIQUE (Codigo_Ref, ID_Curso)
);

-- 2. Fila de Envio (Log & Queue)
CREATE TABLE Log_Comunicacoes (
    ID_Log NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    Remetente VARCHAR2(100) DEFAULT 'noreply@academiadigital.pt',
    Destinatario VARCHAR2(255) NOT NULL,
    Assunto VARCHAR2(200),
    Corpo_HTML CLOB,
    Data_Criacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    Data_Agendada TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    Data_Envio TIMESTAMP,
    Estado VARCHAR2(20) DEFAULT 'PENDENTE' CHECK (Estado IN ('PENDENTE', 'ENVIADO', 'ERRO')),
    Erro_Msg VARCHAR2(4000),
    Contexto_Origem VARCHAR2(50)
);

-- 3. [NOVO v9] Regras de Comunicação (O Cérebro da Automação)
CREATE TABLE Regras_Comunicacao (
    ID_Regra NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    Nome_Regra VARCHAR2(200) NOT NULL,
    ID_Curso NUMBER,
    ID_Modelo NUMBER NOT NULL,
    Momento_Envio NUMBER NOT NULL, -- Ex: -1 (véspera), 1 (dia após), 0 (dia da sessão)
    Exige_Presenca CHAR(1) DEFAULT 'N' CHECK (Exige_Presenca IN ('S','N')),
    Ativo CHAR(1) DEFAULT 'S' CHECK (Ativo IN ('S','N')),
    Descricao VARCHAR2(500),
    CONSTRAINT FK_Regra_Curso FOREIGN KEY (ID_Curso) REFERENCES Cursos(ID_Curso),
    CONSTRAINT FK_Regra_Modelo FOREIGN KEY (ID_Modelo) REFERENCES Modelos_Comunicacao(ID_Modelo)
);

-- SEED DATA (Base Templates e Regras)
INSERT INTO Modelos_Comunicacao (Codigo_Ref, Assunto, Contexto, Corpo_HTML)
VALUES (
    'BOAS_VINDAS', 
    'Bem-vindo à Academia: #CURSO#', 
    'TURMA',
    '<p>Olá <strong>#NOME#</strong>,</p><p>Confirma-se a tua inscrição na turma #TURMA#.</p>'
);

INSERT INTO Modelos_Comunicacao (Codigo_Ref, Assunto, Contexto, Corpo_HTML)
VALUES (
    'LEMBRETE_INICIO', 
    'Lembrete: O teu curso começa amanhã!', 
    'TURMA',
    '<p>Olá <strong>#NOME#</strong>,</p><p>Não te esqueças que o curso #CURSO# começa amanhã, dia #DATA_INICIO#.</p>'
);

INSERT INTO Modelos_Comunicacao (Codigo_Ref, Assunto, Contexto, Corpo_HTML)
VALUES (
    'AGRADECIMENTO_FIM', 
    'Obrigado por participares: #CURSO#', 
    'TURMA',
    '<p>Olá <strong>#NOME#</strong>,</p><p>Agradecemos a tua participação no curso #CURSO#. Esperamos ver-te em breve.</p>'
);

-- Inserir regras base após criar os modelos
INSERT INTO Regras_Comunicacao (Nome_Regra, Momento_Envio, Exige_Presenca, ID_Modelo)
VALUES ('Boas-vindas (D-3)', -3, 'N', (SELECT ID_Modelo FROM Modelos_Comunicacao WHERE Codigo_Ref = 'BOAS_VINDAS'));

INSERT INTO Regras_Comunicacao (Nome_Regra, Momento_Envio, Exige_Presenca, ID_Modelo)
VALUES ('Lembrete de Início (D-1)', -1, 'N', (SELECT ID_Modelo FROM Modelos_Comunicacao WHERE Codigo_Ref = 'LEMBRETE_INICIO'));

INSERT INTO Regras_Comunicacao (Nome_Regra, Momento_Envio, Exige_Presenca, ID_Modelo)
VALUES ('Agradecimento e Feedback (D+1)', 1, 'S', (SELECT ID_Modelo FROM Modelos_Comunicacao WHERE Codigo_Ref = 'AGRADECIMENTO_FIM'));

COMMIT;
